language: ruby
rvm:
  - 2.4.2
install: bundle install
script: jekyll build
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: datalab-usaspending-gov
  skip_cleanup: true
  local_dir: _site
  cache_control: "max-age=21600"
  region: us-gov-west-1
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
